export default {
  multipass: true,
  js2svg: {
    indent: 2,
    pretty: true,
  },
  plugins: [
    // these are enabled in the default preset
    'removeDoctype',
    'removeXMLProcInst',
    'removeComments',
    'removeMetadata',
    'removeEditorsNSData',
    'cleanupAttrs',
    'mergeStyles',
    'inlineStyles',
    'minifyStyles',
    'cleanupIDs',
    'removeUselessDefs',
    'cleanupNumericValues',
    'convertColors',
    'removeUnknownsAndDefaults',
    'removeNonInheritableGroupAttrs',
    'removeUselessStrokeAndFill',
    'removeViewBox',
    'cleanupEnableBackground',
    'removeHiddenElems',
    'removeEmptyText',
    'convertShapeToPath',
    'convertEllipseToCircle',
    'moveElemsAttrsToGroup',
    'moveGroupAttrsToElems',
    'collapseGroups',
    'convertPathData',
    'convertTransform',
    'removeEmptyAttrs',
    'removeEmptyContainers',
    'mergePaths',
    'removeUnusedNS',
    'sortDefsChildren',
    'removeTitle',
    'removeDesc',
    // the following are disabled in the default preset
    'convertStyleToAttrs',
    'removeDimensions',
    { name: 'removeAttrs', params: { attrs: '(data-(\\w*))' } },
    { name: "removeUselessStrokeAndFill", params: { stroke: true, fill: true, removeNone: true } },
    'removeScriptElement',
    'reusePaths',
    { name: "removeAttrs", params: { attrs: "fill", elemSeparator: ":", preserveCurrentColor: false } },
    "removeStyleElement",
    { name: "removeAttrs", params: { attrs: "class", elemSeparator: ":", preserveCurrentColor: false } },
    "removeUselessDefs",
  ]
}
